---
title: "Developing Data Product - Assigment Week 4"
author: "Luccas Betton"
date: "09/12/2021"
output: ioslides_presentation
runtime: shiny
---

```{css,Echo = FALSE}
.pre{
    white-space: pre !important;
    overflow-y: scroll !important;
    overflow-X: scroll !important;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy.opts = list(width.cutoff=60),tidy = TRUE)
```

## Introduction

For this assignment was created a Shiny application to present the miles per galon by weight from the dataset mtcars. The user will be able to set the minium and maximum weight value (y axis minimum and maximum) and filter the data by the types of cylinders.

## Ui.r



```{r,echo = TRUE, results='hide', out.height= "50%"}
library(shiny)
shinyUI(fluidPage(
    titlePanel("Developing Data Prodcuts - Assigment 4"),
    h5("This Application shows the miles per galon by weight from the dataset mtcars"),
    sidebarLayout(
        sidebarPanel(
            sliderInput("Min","Minimum Weight - Y Axis Minium Value",min = 1,max = 5,value = 1),
            sliderInput("Max","Maximum Weight  - Y Axis Maximum Value",min = 2,max = 5,value = 5),
            checkboxGroupInput("cyl","Cylinders Selections",choices = list("Cylinder - 4" = 4,"Cylinder - 6" = 6, "Cylinder - 8" = 8),selected = 4)),
        mainPanel(plotOutput("distPlot"))
    )
))
```

## Server.R

```{r, message = FALSE,warning = FALSE, echo=TRUE,results='hide'}
library(shiny)
library(dplyr)

shinyServer(function(input, output) {

    output$distPlot <- renderPlot({
        
        #Filter by selected cylinders
        data <- filter(mtcars,cyl %in% input$cyl)
        
        # draw the plot considering y minimum and maximum inputs 
        plot(data$mpg,data$wt,xlab = "Miles per Galon", ylab = "Weight", ylim = c(input$Min,input$Max))

    })

})

```

## Thank you!

